# Generated by Django 3.1 on 2020-08-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pizza', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('ingredientes', models.CharField(max_length=200)),
            ],
        ),
    ]
