# Generated by Django 3.1 on 2020-08-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaapp', '0004_ingrediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_ingrediente', models.IntegerField()),
                ('fk_base', models.IntegerField()),
            ],
        ),
    ]
