# Generated by Django 3.1 on 2020-08-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaapp', '0005_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=15)),
                ('fk_ingrediente', models.IntegerField()),
                ('tamano', models.CharField(max_length=15)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=4)),
                ('descuento', models.IntegerField()),
            ],
        ),
    ]
