# Generated by Django 3.1 on 2020-08-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaapp', '0006_combo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
