# Generated by Django 3.1 on 2020-08-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaapp', '0008_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cant',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
