# Generated by Django 3.1 on 2020-08-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaapp', '0009_pedido_cant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cant',
        ),
    ]
